{{- if $.Values.selfSignedClusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ tpl (index .Values.selfSignedCertClusterIssuer) . }}
  namespace: cert-manager
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "2"
spec:
  selfSigned: {}
{{- end }}